services:
    magentix_sylius_mondial_relay_plugin.repository.pickup:
        class: Titi60\SyliusMondialRelayPlugin\Repository\PickupRepository

    magentix_sylius_mondial_relay_shipping_rates.form.type.weight:
        class: Titi60\SyliusMondialRelayPlugin\Form\Type\Shipping\WeightType
        public: true
        tags:
            - { name: form.type }