services:
    app.form.type.shipping_calculator.magentix_mondial_relay:
        class: Titi60\SyliusMondialRelayPlugin\Form\Type\Shipping\Calculator\MondialRelayConfigurationType
        arguments:
            - '@magentix_sylius_mondial_relay_shipping_rates.form.type.weight'
        tags:
            - { name: form.type }

    app.form.type.mondial_relay_shipping_gateway:
        class: Titi60\SyliusMondialRelayPlugin\Form\Type\Shipping\Gateway\MondialRelayShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: "mondial_relay_shipping_gateway", label: "Mondial Relay Gateway" }